# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_chatapp', '0002_auto_20181205_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.TextField(null=True),
        ),
    ]
