# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_chatapp', '0003_pizza_crust'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='user_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_chatapp.User'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='user_id',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
