# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_chatapp', '0004_auto_20181211_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_flag', models.IntegerField()),
                ('delivery_flag', models.IntegerField()),
            ],
        ),
    ]
