# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_chatapp', '0006_flag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='delivery_flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='pickup_flag',
            field=models.IntegerField(null=True),
        ),
    ]
