# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_chatapp', '0007_auto_20181217_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='user_id_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
